### ISSUE TITLE
AssertionError: assert pattern.endswith("!")

### ISSUE THREAD

**Issue by craiglabenz** [andrewgodwin/asgi_redis#3]
[This line](https://github.com/andrewgodwin/asgi_redis/blob/51f8e588efa4324de49dd30c233f1439d18a329a/asgi_redis.py#L136) tests that patterns end with a "!".

However, in the `django-channels` demo project, that is exploding against patterns like:

* `!http.response.?`
* `!websocket.send.?`

Should it potentially be `startswith('!')` ?

> I did not encounter this problem before upgrading to `asgi_redis==0.10.0`.

**Comment by andrewgodwin** [comment]
This actually got changed around - it should now be endswith. The demo project needs fixing.

**Comment by craiglabenz** [comment]
Thanks for the clarity, @andrewgodwin!
