### ISSUE TITLE
Encrypt messages

### ISSUE THREAD

**Issue by onegreyonewhite** [andrewgodwin/asgi_redis#4]
It lacks encryption packets transmitted packets between Django and redis. It would be very cool if it would be possible to encrypt the packets to someone overheard critical data on the channel.
How to look at [here](https://github.com/vingd/encrypted-pickle-python) is the library?

**Comment by andrewgodwin** [comment]
This is already on my roadmap, actually - the plan is to use symmetric cryptography and the `cryptography` package to encode and decode the raw byte strings that we encode messages to using `msgpack`.

**Comment by onegreyonewhite** [comment]
How about to use the class based approach to serialization / deserialization? This would greatly facilitate the task and would enable developers to use their approach to serialization.
I personally would be very balgodaren you for this opportunity, because it could use already encrypted packets in your project.
If you describe your view of what should look like a class, I could help you save your time. Honestly I like [this](https://github.com/niwinz/django-redis/tree/master/django_redis/serializers) approach.

**Comment by andrewgodwin** [comment]
It's much better to encapsulate it in the channel layer, I think - the asgi_redis implementation already has hook points for changing the serialisation so it won't be that hard to implement.

**Comment by andrewgodwin** [comment]
Now implemented in `0.12.0`.

**Comment by onegreyonewhite** [comment]
@andrewgodwin, THANK YOU for your good work!
